### ISSUE TITLE
Error with Envoy Docker

### ISSUE THREAD

**Issue by sderuiter** [bisgardo/concordium-docker#11]
Hi, I feel I'm almost there, but getting a weird error. I've updated all paths to the correct location on my Unraid install, however I can't figure out what to change for the Envoy install?

Any hints?

.env file:
````
NODE_TAG=3.0.1-2_1
NODE_NAME=https://concordium-explorer.nl 
COMPOSE_PROJECT_NAME=mainnet
DOMAIN=mainnet.concordium.software
GENESIS_DATA_FILE=./genesis/mainnet-0.dat
NODE_IMAGE=bisgardo/concordium-node:3.0.1-2_1
NODE_DASHBOARD_IMAGE=bisgardo/concordium-node-dashboard:node-3.0.1-2_1
````

.yaml file:
```
version: '3.9'
services:
  node_oob_catchup:
    image: curlimages/curl:latest
    pull_policy: always
    user: root
    volumes:
    - data:/mnt/cache/appdata/ccdnode/data
    entrypoint:
    - /bin/sh
    - -c
    - |
      [ -f /mnt/cache/appdata/ccdnode/data/blocks.mdb ] ||
        curl -sSf https://catchup.${DOMAIN}/blocks_to_import.mdb -o /mnt/cache/appdata/ccdnode/data/blocks.mdb
  node:
    image: ${NODE_IMAGE}
    entrypoint: /concordium-node
    environment:
    - CONCORDIUM_NODE_DATA_DIR=/mnt/cache/appdata/ccdnode/data
    - CONCORDIUM_NODE_CONFIG_DIR=/mnt/cache/appdata/ccdnode/config
    - CONCORDIUM_NODE_CONSENSUS_IMPORT_BLOCKS_FROM=/mnt/cache/appdata/ccdnode/data/blocks.mdb
    - CONCORDIUM_NODE_CONSENSUS_GENESIS_DATA_FILE=/mnt/cache/appdata/ccdnode/genesis.dat
    - CONCORDIUM_NODE_CONNECTION_BOOTSTRAP_NODES=bootstrap.${DOMAIN}:8888
    - CONCORDIUM_NODE_RPC_SERVER_ADDR=0.0.0.0
    - CONCORDIUM_NODE_PROMETHEUS_SERVER=1
    - CONCORDIUM_NODE_PROMETHEUS_LISTEN_ADDRESSS=0.0.0.0
    # Defer container start until the init containers have completed successfully.
    # Note that no logs are emitted on stdout until all containers have started.
    # Also, this syntax requires Docker Compose v. 1.29+.
    depends_on:
      node_oob_catchup:
        condition: service_completed_successfully
    networks:
    - concordium
    ports:
    - "8888:8888"   # P2P
    - "10000:10000" # gRPC
    - "9090:9090"   # Prometheus (metrics)
    volumes:
    - ${GENESIS_DATA_FILE}:/mnt/cache/appdata/ccdnode/genesis.dat
    - data:/mnt/cache/appdata/ccdnode/data
    - config:/mnt/cache/appdata/ccdnode/config
    build:
      context: .
      args:
        tag: ${NODE_TAG}
  node-collector:
    image: ${NODE_IMAGE}
    entrypoint: /node-collector
    environment:
    - CONCORDIUM_NODE_COLLECTOR_URL=https://dashboard.${DOMAIN}/nodes/post
    - CONCORDIUM_NODE_COLLECTOR_GRPC_HOST=http://node:10000
    - CONCORDIUM_NODE_COLLECTOR_NODE_NAME=${NODE_NAME}
    depends_on:
    - node
    networks:
    - concordium
    restart: on-failure # service may time out before the node is operational
  node-dashboard-grpc-proxy:
    image: envoyproxy/envoy:v1.18-latest
    pull_policy: always
    entrypoint: /usr/local/bin/envoy --config-path /etc/envoy/envoy.yaml
    depends_on:
    - node
    networks:
    - concordium
    ports:
    - "9901:9901" # admin
    - "9999:9999" # proxy
    volumes:
    - ./node-dashboard/envoy.yaml:/etc/envoy/envoy.yaml:ro
  node-dashboard:
    image: ${NODE_DASHBOARD_IMAGE}
    depends_on:
    - node-dashboard-grpc-proxy
    networks:
    - concordium
    ports:
    - "8099:80" # web
    build:
      context: ./node-dashboard
      args:
        tag: main
volumes:
  data:
  config:
networks:
  concordium:
```
```
Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: 
process_linux.go:495: container init caused: rootfs_linux.go:60: mounting
 "/boot/config/plugins/compose.manager/projects/bisgardo/node-dashboard/envoy.yaml" 
to rootfs at "/var/lib/docker/btrfs/subvolumes/a96c66fb08d1462628c64dc89188004102cf4c320738bd40abf457d5d1d6c1ae/etc/envoy/envoy.yaml" 
caused: not a directory: unknown: 
Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type```

**Comment by bisgardo** [comment]
I don't think this relates to your error, but to be clear, the paths that you changed are all inside the Docker containers. The host volumes `data` and `config` are managed by Docker (see `docker volume ls` and `docker volume inspect <name>` for details). If you want them to be mounted to specific host directories you need to change the left part of the `volume` entries to absolute or relative (prefixed with `./`) paths.

But for your particular error, it looks like `/boot/config/plugins/compose.manager/projects/bisgardo/node-dashboard/envoy.yaml` is a directory. Did you accidentally create that somehow?

What exact command are you running and from what working directory? The config assumes that the file `./node-dashboard/envoy.yaml` is available relative to that dir.

**Comment by sderuiter** [comment]
Thank you for your reply. I looked at the file structure and indeed that envoy.yaml directory is present (and created somehow by the command). 

I’m using compose manager plugin on unraid to run this, not immediately clear what command is being run, will investigate (and try to change the paths as well).

**Comment by sderuiter** [comment]
I've updated all volumes to point to a local location.

I've run the following command in the folder `/mnt/cache/appdata/ccdnode`:

`docker-compose --env-file mainnet.env --project-name=mainnet up`,

where mainnet.nev:
```
NODE_NAME=https://concordium-explorer.nl
NODE_TAG=3.0.1-2_1
COMPOSE_PROJECT_NAME=mainnet
DOMAIN=mainnet.concordium.software
GENESIS_DATA_FILE=./genesis/mainnet-0.dat
NODE_IMAGE=bisgardo/concordium-node:3.0.1-2_1
NODE_DASHBOARD_IMAGE=bisgardo/concordium-node-dashboard:node-3.0.1-2_1
```

and docker-compose.yml:
``` 
version: '3.9'
services:
  node_oob_catchup:
    image: curlimages/curl:latest
    pull_policy: always
    user: root
    volumes:
    - /mnt/cache/appdata/ccdnode/data:/mnt/data
    entrypoint:
    - /bin/sh
    - -c
    - |
      [ -f /mnt/data/blocks.mdb ] ||
        curl -sSf https://catchup.${DOMAIN}/blocks_to_import.mdb -o /mnt/data/blocks.mdb
  node:
    image: ${NODE_IMAGE}
    entrypoint: /concordium-node
    environment:
    - CONCORDIUM_NODE_DATA_DIR=/mnt/data
    - CONCORDIUM_NODE_CONFIG_DIR=/mnt/config
    - CONCORDIUM_NODE_CONSENSUS_IMPORT_BLOCKS_FROM=/mnt/data/blocks.mdb
    - CONCORDIUM_NODE_CONSENSUS_GENESIS_DATA_FILE=/mnt/genesis.dat
    - CONCORDIUM_NODE_CONNECTION_BOOTSTRAP_NODES=bootstrap.${DOMAIN}:8888
    - CONCORDIUM_NODE_RPC_SERVER_ADDR=0.0.0.0
    - CONCORDIUM_NODE_PROMETHEUS_SERVER=1
    - CONCORDIUM_NODE_PROMETHEUS_LISTEN_ADDRESSS=0.0.0.0
    # Defer container start until the init containers have completed successfully.
    # Note that no logs are emitted on stdout until all containers have started.
    # Also, this syntax requires Docker Compose v. 1.29+.
    depends_on:
      node_oob_catchup:
        condition: service_completed_successfully
    networks:
    - concordium
    ports:
    - "8888:8888"   # P2P
    - "10000:10000" # gRPC
    - "9090:9090"   # Prometheus (metrics)
    volumes:
    - /mnt/cache/appdata/ccdnode/${GENESIS_DATA_FILE}:/mnt/genesis.dat
    - /mnt/cache/appdata/ccdnode/data:/mnt/data
    - /mnt/cache/appdata/ccdnode/config:/mnt/config
    build:
      context: .
      args:
        tag: ${NODE_TAG}
  node-collector:
    image: ${NODE_IMAGE}
    entrypoint: /node-collector
    environment:
    - CONCORDIUM_NODE_COLLECTOR_URL=https://dashboard.${DOMAIN}/nodes/post
    - CONCORDIUM_NODE_COLLECTOR_GRPC_HOST=http://node:10000
    - CONCORDIUM_NODE_COLLECTOR_NODE_NAME=${NODE_NAME}
    depends_on:
    - node
    networks:
    - concordium
    restart: on-failure # service may time out before the node is operational
  node-dashboard-grpc-proxy:
    image: envoyproxy/envoy:v1.18-latest
    pull_policy: always
    entrypoint: /usr/local/bin/envoy --config-path /etc/envoy/envoy.yaml
    depends_on:
    - node
    networks:
    - concordium
    ports:
    - "9901:9901" # admin
    - "9999:9999" # proxy
    volumes:
    - /mnt/cache/appdata/ccdnode/node-dashboard/envoy.yaml:/etc/envoy/envoy.yaml:ro
  node-dashboard:
    image: ${NODE_DASHBOARD_IMAGE}
    depends_on:
    - node-dashboard-grpc-proxy
    networks:
    - concordium
    ports:
    - "8099:80" # web
    build:
      context: ./node-dashboard
      args:
        tag: main
volumes:
  data:
  config:
networks:
  concordium:
```

This pulls all images, but then the following error occurs:

```
2 errors occurred:
	* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /mnt/cache/appdata/ccdnode/node-dashboard/Dockerfile: no such file or directory
	* unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /mnt/cache/appdata/ccdnode/Dockerfile: no such file or directory
```

If I run the same docker-compose command again, these errors do not occur.

Note that I had to copy the envoy.yaml file manually to this location `/mnt/cache/appdata/ccdnode/node-dashboard/envoy.yaml`, otherwise I would get the error mentioned above (dir vs file). 

It seems the node is running (it's log says it's receiving blocks), but the other containers have stopped. I've started all containers again (except the catchup), and they keep running, but the node dashboard at port 8099 reports:

`Failed polling node
With error message: Http response at 400 or 500 level`

Getting closer!

**Comment by sderuiter** [comment]
Addendum: the node-collector logs have the following entry:
`INFO: Collecting node information via gRPC from https://concordium-explorer.nl/http://node:10000/rpcadmin`

Can this be related to the node-dashboard reporting a 400/500 HTTP error?

**Comment by bisgardo** [comment]
Glad to hear :+1:

The project expects to be run from the root directory of your project or, more precisely, that all the files it needs are available in the specific paths relative to the current working directory. Instead of copying `envoy.yaml` you could just replace `/mnt/cache/appdata/ccdnode/node-dashboard/envoy.yaml` in the volume binding with it's actual location wherever it is.

The errors indicate that Compose tried to build the images but couldn't find the Dockerfiles for the same reason as above. Not sure why you didn't get the same error the second time. Did you somehow pull the public images in between and/or pass `--no-build`?

The node-collector logs indicate that the node is indeed up. Your node is also shown to be catching up correctly on the [dashboard](https://dashboard.mainnet.concordium.software/node/0a5c3c2b08fb3cda).

The node dashboard is a completely independent component that only depends on the Envoy and the node. I just tried it and it's up for me on `http://localhost:8099`. I think the node has to be completely caught up before it starts its gRPC server (which the node dashboard uses). It may also be because you're using out-of-band catchup (this is also the reason why you don't have any peers btw.). Not competely sure. Maybe there are hints in the Envoy logs.

In any case, try waiting until the node has caught up - this will take a while ;)

**Comment by sderuiter** [comment]
Restarted everything again after being bitten by having 2 nodes on the same external IP...but the good news is, it's working again, thanks!
